apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dev
  labels:
    app: wordpress-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-dev
  template:
    metadata:
      labels:
        app: wordpress-dev
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.Tag }}"
          ports:
          - containerPort: {{ .Values.port }}
          volumeMounts:
          - name: wordpress-vol
            mountPath: /var/www/html/wp-config.php
            subPath: wp-config.php
            readOnly: true
      volumes:
      - name: wordpress-vol
        configMap:
          name: wordpress-config

          
