apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-wordpress"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /

  name: wordpress-dev-ingress
spec:
  rules:
  - host: dev.exahost.com
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: wordpress-dev
                port:
                  number: 80
tls:
- hosts:
  - dev.exahost.com
  secretName: wordpress-dev
