apiVersion: v1
kind: Service
metadata:
  name: wordpress-dev
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: {{ .Values.port }}
    nodePort: 30007
  selector:
    app: wordpress-dev
